name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
      with:
        runtime: node@24
        cache: true
        install: 'true'
    - name: Typecheck
      run: pnpm typecheck
    - name: Lint
      run: pnpm lint
    - name: Test
      run: pnpm test:ci
    - name: Build
      run: pnpm build
